<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>true</UseWPF>
    <AssemblyName>installer-soundcloud</AssemblyName>
    <RootNamespace>Setup</RootNamespace>
    <Product>SoundCloud Desktop Setup</Product>
    <Version>1.4.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\WpfApp1\assets\icon.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.IO.Compression" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\WpfApp1\Strings.cs" Link="Strings.cs" />
    <Resource Include="..\WpfApp1\assets\sc-icon.png">
      <Link>sc-icon.png</Link>
    </Resource>
    <EmbeddedResource Include="payload\app.zip" Condition="Exists('payload\app.zip')" />
    <EmbeddedResource Include="$(NuGetPackageRoot)wpf-ui\4.3.0\lib\net472\Wpf.Ui.dll">
      <Link>lib\Wpf.Ui.dll</Link>
      <LogicalName>Setup.lib.Wpf.Ui.dll</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="$(NuGetPackageRoot)wpf-ui.abstractions\4.3.0\lib\net472\Wpf.Ui.Abstractions.dll">
      <Link>lib\Wpf.Ui.Abstractions.dll</Link>
      <LogicalName>Setup.lib.Wpf.Ui.Abstractions.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
